### ISSUE TITLE
Anchors for small objects

### ISSUE THREAD

**Issue by RomRoc** [mnslarcher/kmeans-anchors-ratios#10]
Hello @mnslarcher thanks for your excellent repo.

My dataset images are 3120x3120, I use efficientdet model is D8, so input_size = 1536. I have small objects, in the original image size the width and height of boxes are in range 6-60 px.
When I run your tutorial on my dataset, I get various bboxes without similar anchors, and your tutorial is right!

In your opinion, should I reduce `anchors_ratios` to make anchors smaller, so they are more similar to resized dataset?
For example if I use `anchors_ratios = [(0.2, 0.4), (0.3, 0.3), (0.4, 0.2)]` I get empty bboxes list without similar anchors.

Thanks

**Comment by mnslarcher** [comment]
Hi @RomRoc, no, the parameters that are supposed to control the size are anchor_scale and anchors_scales (the original names are a little bit confusing) you should change them when you train EfficientDet, see also: https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/204

6 px is really super small, in any case I would also consider to:
1) Divide the problem in more than one stage (if possibile): e.g. first I find all the cars and then all the cars' wheels on a crop of the car with full resolution (no resize). This I think is most of the time the best approach (when feasible)
2) Divide the images in more than one part with some overlap between the parts so every part can be fed into the model at the original resolution
3) increase the input_size of your EfficientDet (if your GPU have a lot of RAM), you are not obliged to keep it as suggested

**Comment by RomRoc** [comment]
Thanks, I will divide original image in tiles to feed model with image in original resolution.
Bye
