### ISSUE TITLE
How to kmeans anchors_scales?

### ISSUE THREAD

**Issue by GoogleWiki** [mnslarcher/kmeans-anchors-ratios#2]
How to kmeans anchors_scales together with anchors_ratios, thanks.

**Comment by mnslarcher** [comment]
Hi @GoogleWiki, I believe that tuning anchor scales is less important than tuning ratios. For example, EfficientDet by default use 15 different sizes (3 anchor scales x 5 levels), going from 32x32 pixels up to 512x512 (the full input for EfficientDet0).

The only thing that I would check is if in your dataset you have bounding boxes that have a size lower than 32x32 AFTER rescaling.

For example, if your image is 1024x1024 and you have an object that have a size around 34x34 pixels, after rescaling the image to 512x512, your object (and its bounding box) will be 17x17, too small to be considered by the network during training.

Even in this case, more than changing the anchor sizes, is more likely that it would be better to change the input size, using for example 1024x1024.

**Comment by GoogleWiki** [comment]
Most objects of my dataset is between 10x10 to 100x100 in 1024 sized images. That's much smaller than COCO and VOC. So the big anchor scale setting is a wasting of computation, and also harmful for performance. Thanks for your help. I will run a scale kmeans on scales based on your code. Thanks again.
