### ISSUE TITLE
Is the 'input_size' is  size of input image or efficientdet default input size ?

### ISSUE THREAD

**Issue by Samjith888** [mnslarcher/kmeans-anchors-ratios#4]
I have images with size 4096x2040 and also very lesser size.Total images is 60k . Efficientdet-d0 default size is 512.
I got the following result when i run the default command u mentioned in the tutorial.

```
[06/04 17:42:26] Starting the calculation of the optimal anchors ratios
[06/04 17:42:26] Extracting and preprocessing bounding boxes
[06/04 17:42:27] Discarding 0 bounding boxes with size lower or equal to 0
[06/04 17:42:27] K-Means (10 runs): 100%|███████████████| 10/10 [00:18<00:00,  1.86s/it]
[06/04 17:42:46] Runs avg. IoU: 86.78% ± 0.00% (mean ± std. dev. of 10 runs, 0 skipped)
[06/04 17:42:46] Avg. IoU between bboxes and their most similar anchors after normalizing them so that they have the same area (only the anchor ratios matter): 86.79%
[06/04 17:42:46] Avg. IoU between bboxes and their most similar anchors (no normalization, both anchor ratios and sizes matter): 33.88%
[06/04 17:42:47] Num. bboxes with similar anchors (IoU >= 0.5):  149025/401558 (37.11%)
[06/04 17:42:47] Optimal anchors ratios: [(0.6, 1.6), (0.8, 1.3), (1.0, 1.0)]

```

 Here what should i gave as input size actually?

**Comment by mnslarcher** [comment]
Hi @Samjith888, As you said, for EfficientDet0 the default input size is 512.

If you are using the TensorFlow implementation and you want to change it you have to change this [config](https://github.com/google/automl/blob/master/efficientdet/hparams_config.py) I guess (I'm using [this](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch) PyTorch implementation so I'm not 100% sure):

```
    'efficientdet-d0':
        dict(
            name='efficientdet-d0',
            backbone_name='efficientnet-b0',
            image_size=512,
            fpn_num_filters=64,
            fpn_cell_repeats=3,
            box_class_repeats=3,
        ),
```
Or probably better launch [main](https://github.com/google/automl/blob/aff52f6fac580607d0982fcc2bd2747d33115fa1/efficientdet/main.py) using hparams:
```
flags.DEFINE_string(
    'hparams', '', 'Comma separated k=v pairs of hyperparameters or a module'
    ' containing attributes to use as hyperparameters.')
```

If you have enough RAM you can also consider to use EfficientDetX with X > 0, given that input_size grow with X. For example If you have enough resourses for EfficientDet7 the default input_size is a lot larger:
```
    'efficientdet-d7':
        dict(
            name='efficientdet-d7',
            backbone_name='efficientnet-b6',
            image_size=1536,
            fpn_num_filters=384,
            fpn_cell_repeats=8,
            box_class_repeats=5,
            anchor_scale=5.0,
            fpn_name='bifpn_sum',  # Use unweighted sum for training stability.
        ),
```

Another option is to change the scales of the anchors, again I'm not using the TF implementation but I think you need to change:
```
  h.num_scales = 3
  h.anchor_scale = 4.0
```
The first one tells you how many scales for each layer and the second one is a constant used to calculate the size of all the anchors.

[Here](https://github.com/google/automl/blob/aff52f6fac580607d0982fcc2bd2747d33115fa1/efficientdet/anchors.py) you can find more details about the impact of these hps.

The number of anchors is num_scales * num_ratios * 5 (layers in the pyramid).

Returning to your question, if you are using EfficientDet0 with the default hyper-parameters you need to call the function in this way (like you probably already did if you followed the tutorial):

```
## change the following parameters according to your model:

# efficientdet0 input size
INPUT_SIZE = 512
# efficientdet default sizes
ANCHORS_SIZES = (np.sqrt([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]) * 
                 np.array([32, 64, 128, 256, 512])[:, np.newaxis]).flatten().tolist()
ANCHORS_SIZES

from kmeans_anchors_ratios import get_optimal_anchors_ratios

anchors_ratios = get_optimal_anchors_ratios(
    instances,
    anchors_sizes=ANCHORS_SIZES,
    input_size=INPUT_SIZE,
    normalizes_bboxes=True,
    num_runs=10,
    num_anchors_ratios=3,
    max_iter=300,
    iou_threshold=0.5,
    min_size=0,
    decimals=1,
)
```
From you results you are missing small objects and to summarize you can take one or more of these actions:
1. Change input_size, or directly or indirectly using a larger EfficientDetX
2. Change ancor_scale / num_scales
3. If you can, split the problem in two part, for example the first Detector understand where the small objects are located and a second detector takes as input just the crop identified by the first detector. This work in case like you want identify a part of an object, maybe the part is very small but you can first indentfy the object (like a building), crop it and then identify the part (like a window) in this way the size of your object for the Detector will be lager
