### ISSUE TITLE
results are quite different from Cli98

### ISSUE THREAD

**Issue by edwardning** [mnslarcher/kmeans-anchors-ratios#5]
Hi.
Now I want to get anchors of my own datasets.

Result from https://github.com/Cli98/anchor_computation_tool is:
anchors_scales = [8.3, 3.3, 18.0],
anchors_ratios = [(1, 1.02), (1, 0.92), (1, 0.97)]

Result from yours:
anchors_ratios =  [(0.7, 1.4), (1.0, 1.0), (1.3, 0.8)]

It seem quite different! 
I'm really confused, and could you give an explain?
I also want to know how to get anchors_scales in your code?

Thanks a lot!

**Comment by mnslarcher** [comment]
Hi @edwardning, in the tutorial of the repo that you linked as I commented [here](https://github.com/Cli98/anchor_computation_tool/issues/6) the bounding boxes aren't normalized before running K-Means and I think this is a very bad idea given how K-Means with IoU works.

From the issue linked above:

> Immagine this situation:
> 10 bboxes 10x5
> 5 bboxes 2x1
> 5 bboxes 1x2
> 
> If K=2 the two clusters would be:
> 10 bboxes 10x5
> 
> and
> 5 bboxes 2x1
> 5 bboxes 1x2
> 
> and so the suggested ratios would be (1.4, 0.7) and (1., 1.) instead of (1.4, 0.7) and (0.7, 1.4) (or (1., 0.5), (1., 2.)).

As you can see from this example if you don't normalize, K-Means will be driven mainly by the bounding boxes sizes and your ratios will not make much sense.

Evan if you want to search for what the original TensorFlow repo calls the anchor_scale in the same K-Means run, you should consider that in EfficientDet (if you are using EfficientDet like I'm assuming) your sizes are determined by three factor: num_scales, anchor_scale and the layers.

The number of anchors generated is: num_ratios * num_scales * 5 (layers in the pyramid).

The repo that you linked doesn't consider this in the tutorial.

Also, you should use anchor ratios with a area (approximately) of 1, the normalization done in the tutorial of the repo that you linked is not correct considering how anchor ratios are used by the EfficientDet implementations.

Also, you should consider the input_size and adapt your bounding boxes to it before running K-Means to search for optimal scales.

See also [this](https://github.com/mnslarcher/kmeans-anchors-ratios/issues/4) issue if you have the problem that in your dataset some bounding boxes are very small, if you haven't this problem probably the default sizes are already very good.

You can test how good one combination of sizes and ratios are using `get_annotations_without_similar_anchors`, see the tutorial of this repo.

Note that this list of sizes:
```
[32.0,
 35.91878554589994,
 40.31747359663594,
 64.0,
 71.83757109179987,
 80.63494719327188,
 128.0,
 143.67514218359975,
 161.26989438654377,
 256.0,
 287.3502843671995,
 322.53978877308754,
 512.0,
 574.700568734399,
 645.0795775461751]
```
Are what the official repo generated when you pass anchor_scale = 4 (the default value), you can easily play with sizes adapting this list based on your anchor_scale.
