### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'int' and 'str'

### ISSUE THREAD

**Issue by liufengwei520** [mnslarcher/kmeans-anchors-ratios#6]
D:\Model\kmeans-anchors-ratios>python kmeans_anchors_ratios.py --instance D:\cocodata\data\COCO2\annotations\instances_train2017.json  --anchors-sizes 32 64 128 256 512 --input-size 512 --normalizes-bboxes True --num-runs 3 --num-anchors-ratios 3
[07/20 23:52:45] Reading D:\cocodata\data\COCO2\annotations\instances_train2017.json
[07/20 23:52:45] Starting the calculation of the optimal anchors ratios
[07/20 23:52:45] Extracting and preprocessing bounding boxes
Traceback (most recent call last):
  File "kmeans_anchors_ratios.py", line 494, in <module>
    _ = get_optimal_anchors_ratios(**args)
  File "kmeans_anchors_ratios.py", line 350, in get_optimal_anchors_ratios
    bboxes = get_bboxes_adapted_to_input_size(instances, input_size)
  File "kmeans_anchors_ratios.py", line 241, in get_bboxes_adapted_to_input_size
    for ann in instances["images"]
  File "kmeans_anchors_ratios.py", line 241, in <dictcomp>
    for ann in instances["images"]
TypeError: unsupported operand type(s) for /: 'int' and 'str'

**Comment by mnslarcher** [comment]
Hi @liufengwei520, have you also tried using the notebook tutorial? If yes, do you get the same error? Do you have the last version of the code (if not, do a git pull)?

**Comment by liufengwei520** [comment]
Yes ,I got the same error in the notebook tutorial,But I have corrected it. I make that  in the file"kmeans_anchor_ratios.py":
add 'int' before ann["width"] and ann["height"] 

the operation is as follow:

scale_factors = {
    ann["id"]: input_size / max(int(ann["width"]), int(ann["height"]))
    for ann in instances["images"]


}

**Comment by liufengwei520** [comment]
Yes ,I got the same error in the notebook tutorial,But I have corrected it. I make that :
add 'int' before ann["width"] and ann["height"]
scale_factors = {
    ann["id"]: input_size / max(int(ann["width"]), int(ann["height"]))
    for ann in instances["images"]


}





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mario Namtao Shianti Larcher"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午3:05
收件人: "mnslarcher/kmeans-anchors-ratios"<kmeans-anchors-ratios@noreply.github.com&gt;; 
抄送: "刘丰玮"<379781908@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [mnslarcher/kmeans-anchors-ratios] TypeError: unsupported operand type(s) for /: &#39;int&#39; and &#39;str&#39; (#6)





 
Hi @liufengwei520, have you also tried using the notebook tutorial? If yes, do you get the same error? Do you have the last version of the code (if not, do a git pull)?

**Comment by mnslarcher** [comment]
Great @liufengwei520, I'm glad you fix it! your file is not the original coco train 2017 right? because in that case width and height are already int, no need to cast them explicitly

**Comment by liufengwei520** [comment]
yes,my dataset is not the original coco dataset，but I make it  as the same as the coco style.thank for your contribution of this tools 
.It is really very nice and helpful .

**Comment by mnslarcher** [comment]
> yes,my dataset is not the original coco dataset，but I make it as the same as the coco style.thank for your contribution of this tools
> .It is really very nice and helpful .

Thanks @liufengwei520! it's a pleasure to know that someone else finds it useful

**Comment by liufengwei520** [comment]
Wow,you again help me find a important error in my annotations of instance_2017.json.  the width and height in coco is int ,but in my annotation these are string.I'm very appreciate for your help.there 're not the words in the world to describe my gratitude for your help.

**Comment by mnslarcher** [comment]
> Wow,you again help me find a important error in my annotations of instance_2017.json. the width and height in coco is int ,but in my annotation these are string.I'm very appreciate for your help.there 're not the words in the world to describe my gratitude for your help.

I haven't done much but I'm glad it was useful for you @liufengwei520 :)!
