### ISSUE TITLE
  File "kmeans_anchors_ratios.py", line 185     f"[{datetime.now().strftime('%m/%d %H:%M:%S')}] "

### ISSUE THREAD

**Issue by AliMedVisionTech** [mnslarcher/kmeans-anchors-ratios#7]
thanks for your code. i am trying to get kmeans-anchors-ratios using medical images dataset but i am having this problem. This is my query.........python kmeans_anchors_ratios.py --instances /home/cuilei/kmeans-anchors-ratios-master/icpr2014/train/xml  --anchors-sizes 32 64 128 256 512 --input-size 512 --normalizes-bboxes True --num-runs 3 --num-anchors-ratios 3 --max-iter 300 --min-size 0 --iou-threshold 0.5 --decimals 1 --default-anchors-ratios '[(0.7, 1.4), (1.0, 1.0), (1.4, 0.7)]'

**Comment by mnslarcher** [comment]
Hi @haideralimughal , I need more details to try to understand where is your problem (at least the full error message) but if I have to guess you are using PASCAL VOC and not COCO format for your annotation (xml and not json). The script expect that your annotations are in COCO format (and so a json file).

If this is your problem, you have first to convert your annotations using a script that you can find for example [here](https://github.com/roboflow-ai/voc2coco).
