### ISSUE TITLE
-input-size

### ISSUE THREAD

**Issue by JK-Pair** [mnslarcher/kmeans-anchors-ratios#8]
Hello,

Input-size, according to which each image is resized before being processed by the model.

if I have 1280x1024 input size, Can I add black to the images (from 1024 to 1280) or Do I have to resize the image to 1280x1280 regardless of the aspect ratio. 

Thank you for your reply.

**Comment by mnslarcher** [comment]
Hi @JK-Pair !, This library doesn't care about how do you reach your target size (you don't have to give images as input to this script, just the json with the ground truth annotations). 

So, in both cases set the `input_size=1280`. :)

Let me know if you have further doubts.

**Comment by JK-Pair** [comment]
> Hi @JK-Pair !, This library doesn't care about how do you reach your target size (you don't have to give images as input to this script, just the json with the ground truth annotations).
> 
> So, in both cases set the `input_size=1280`. :)
> 
> Let me know if you have further doubts.

Do you mean if I have 1280x1040 I can set the input_size=1280 without having to resize the image or edit JSON file(from 1280x1024 to 1280x1280) ?

**Comment by mnslarcher** [comment]
> > Hi @JK-Pair !, This library doesn't care about how do you reach your target size (you don't have to give images as input to this script, just the json with the ground truth annotations).
> 
> > 
> 
> > So, in both cases set the `input_size=1280`. :)
> 
> > 
> 
> > Let me know if you have further doubts.
> 
> 
> 
> Do you mean if I have 1280x1040 I can set the input_size=1280 without having to resize the image or edit JSON file(from 1280x1024 to 1280x1280) ?
> 
> 

Yes, you will change the size of you images before training your model (and probably the library that you will use will do this for you after you pass an input size) here this repo trust you in passing the same input size that you will choose before training.

Thinking better about it, the only problem would be if you'll make your images 1280 with resizing instead of padding. In that case the aspect ratio of your bounding boxes will change. In general, is not a good idea to do it, is more common in object detection to add a black border to avoid any deformation. Many library do this for you when you'll choose the input size. 

This library assume that you will change the size of your image without changing the aspect ratio of you bounding boxes.

If is still not completely clear if you tell me which repo you will use to train you model maybe I can give you a more concrete example.

**Comment by JK-Pair** [comment]
> > > Hi @JK-Pair !, This library doesn't care about how do you reach your target size (you don't have to give images as input to this script, just the json with the ground truth annotations).
> > 
> > 
> > > 
> > 
> > 
> > > So, in both cases set the `input_size=1280`. :)
> > 
> > 
> > > 
> > 
> > 
> > > Let me know if you have further doubts.
> > 
> > 
> > Do you mean if I have 1280x1040 I can set the input_size=1280 without having to resize the image or edit JSON file(from 1280x1024 to 1280x1280) ?
> 
> Yes, you will change the size of you images before training your model (and probably the library that you will use will do this for you after you pass an input size) here this repo trust you in passing the same input size that you will choose before training.
> 
> Thinking better about it, the only problem would be if you'll make your images 1280 with resizing instead of padding. In that case the aspect ratio of your bounding boxes will change. In general, is not a good idea to do it, is more common in object detection to add a black border to avoid any deformation. Many library do this for you when you'll choose the input size.
> 
> This library assume that you will change the size of your image without changing the aspect ratio of you bounding boxes.
> 
> If is still not completely clear if you tell me which repo you will use to train you model maybe I can give you a more concrete example.

Thank you a lot for your help, I used google/automl repo, efficientDet model.

**Comment by mnslarcher** [comment]
> > > > Hi @JK-Pair !, This library doesn't care about how do you reach your target size (you don't have to give images as input to this script, just the json with the ground truth annotations).
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > So, in both cases set the `input_size=1280`. :)
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Let me know if you have further doubts.
> > > 
> > > 
> > > Do you mean if I have 1280x1040 I can set the input_size=1280 without having to resize the image or edit JSON file(from 1280x1024 to 1280x1280) ?
> > 
> > 
> > Yes, you will change the size of you images before training your model (and probably the library that you will use will do this for you after you pass an input size) here this repo trust you in passing the same input size that you will choose before training.
> > Thinking better about it, the only problem would be if you'll make your images 1280 with resizing instead of padding. In that case the aspect ratio of your bounding boxes will change. In general, is not a good idea to do it, is more common in object detection to add a black border to avoid any deformation. Many library do this for you when you'll choose the input size.
> > This library assume that you will change the size of your image without changing the aspect ratio of you bounding boxes.
> > If is still not completely clear if you tell me which repo you will use to train you model maybe I can give you a more concrete example.
> 
> Thank you a lot for your help, I used google/automl repo, efficientDet model.

In this case you don't choose the input size but is the library that choose it for you when you select EfficientDet0, EfficientDet1, EfficientDet2, ..., etc (you can also decide to change it but as you can read in the paper they optimized the architecture for each input size so is a good idea to use that input size if you don't have strong reason to change it)

See here: https://github.com/google/automl/blob/1ec78d22aa9f8b7d33b9cf3a177e05dcc6b4a093/efficientdet/hparams_config.py

For example if you choose efficientdet-d0 your input size will be 512 and so you will have to choose the same number here. If you have a good GPU (with enough RAM), you can also try efficientdet-d5 or efficientdet-d6 that have an input size of 1280. You don't have to manually reisize you images, is done automatically by the EfficientDet repo.

**Comment by JK-Pair** [comment]
> > > > > Hi @JK-Pair !, This library doesn't care about how do you reach your target size (you don't have to give images as input to this script, just the json with the ground truth annotations).
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > So, in both cases set the `input_size=1280`. :)
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Let me know if you have further doubts.
> > > > 
> > > > 
> > > > Do you mean if I have 1280x1040 I can set the input_size=1280 without having to resize the image or edit JSON file(from 1280x1024 to 1280x1280) ?
> > > 
> > > 
> > > Yes, you will change the size of you images before training your model (and probably the library that you will use will do this for you after you pass an input size) here this repo trust you in passing the same input size that you will choose before training.
> > > Thinking better about it, the only problem would be if you'll make your images 1280 with resizing instead of padding. In that case the aspect ratio of your bounding boxes will change. In general, is not a good idea to do it, is more common in object detection to add a black border to avoid any deformation. Many library do this for you when you'll choose the input size.
> > > This library assume that you will change the size of your image without changing the aspect ratio of you bounding boxes.
> > > If is still not completely clear if you tell me which repo you will use to train you model maybe I can give you a more concrete example.
> > 
> > 
> > Thank you a lot for your help, I used google/automl repo, efficientDet model.
> 
> In this case you don't choose the input size but is the library that choose it for you when you select EfficientDet0, EfficientDet1, EfficientDet2, ..., etc (you can also decide to change it but as you can read in the paper they optimized the architecture for each input size so is a good idea to use that input size if you don't have strong reason to change it)
> 
> See here: https://github.com/google/automl/blob/1ec78d22aa9f8b7d33b9cf3a177e05dcc6b4a093/efficientdet/hparams_config.py
> 
> For example if you choose efficientdet-d0 your input size will be 512 and so you will have to choose the same number here. If you have a good GPU (with enough RAM), you can also try efficientdet-d5 or efficientdet-d6 that have an input size of 1280. You don't have to manually reisize you images, is done automatically by the EfficientDet repo.

Thank you so much for your help
