### ISSUE TITLE
EfficientDetD7 tutorial

### ISSUE THREAD

**Issue by RomRoc** [mnslarcher/kmeans-anchors-ratios#9]
Hello, thanks for your excellent repo.
I'm using [this](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch) EfficientDet implementation, like you.

I need to use D7 because I have large images 4160x3120 px with small objects. Objects size don't vary a lot, height and width are 20 to 200 px (for example bbox are 30x150, 180x60, ...)

How should I modify your [notebook tutorial](https://github.com/mnslarcher/kmeans-anchors-ratios/blob/master/tutorial.ipynb)  for EfficientDetD7 ? Should I change only INPUT_SIZE param?

Thanks a lot

**Comment by mnslarcher** [comment]
> Hello, thanks for your excellent repo.
> I'm using [this](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch) EfficientDet implementation, like you.
> 
> I need to use D7 because I have large images 4160x3120 px with small objects. Objects size don't vary a lot, height and width are 20 to 200 px (for example bbox are 30x150, 180x60, ...)
> 
> How should I modify your [notebook tutorial](https://github.com/mnslarcher/kmeans-anchors-ratios/blob/master/tutorial.ipynb) for EfficientDetD7 ? Should I change only INPUT_SIZE param?
> 
> Thanks a lot

Hi @RomRoc, thanks for appreciating this repo!

You need to change the `INPUT_SIZE` and also the `ANCHORS_SIZES` because D7 use a different `anchor_scale` (5 instead of 4 like all the others Dx) as you can see [here](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/c533bc2de65135a6fe1d25ca437765c630943afb/backbone.py#L21)

So change this:
```
# efficientdet0 input size
INPUT_SIZE = 512
# efficientdet default sizes
ANCHORS_SIZES = (4 * np.sqrt([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]) * 
                 np.array([2 ** 3, 2 ** 4, 2 ** 5, 2 ** 6, 2 ** 7])[:, np.newaxis]).flatten().tolist()
ANCHORS_SIZES
```
With this:
```
# efficientdet7 input size
INPUT_SIZE = 1536
# efficientdet default sizes
ANCHORS_SIZES = (5 * np.sqrt([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]) * 
                 np.array([2 ** 3, 2 ** 4, 2 ** 5, 2 ** 6, 2 ** 7])[:, np.newaxis]).flatten().tolist()
ANCHORS_SIZES
```

The rest should remain the same

**Comment by RomRoc** [comment]
Thanks a lot @mnslarcher 
I will use D8, so that I don't have to change even `anchor_scale`

Looking to [utils](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientdet/utils.py) file, it seems it doesn't perform `np.sqrt` to calculate `ANCHORS_SIZES` .
In this case even your tutorial shouldn't use sqrt to be consistent with that EfficientDet implementation?
Thanks

**Comment by mnslarcher** [comment]
> Thanks a lot @mnslarcher
> I will use D8, so that I don't have to change even `anchor_scale`
> 
> Looking to [utils](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientdet/utils.py) file, it seems it doesn't perform `np.sqrt` to calculate `ANCHORS_SIZES` .
> In this case even your tutorial shouldn't use sqrt to be consistent with that EfficientDet implementation?
> Thanks

You are right, no need to put a sqrt there, I'll update that, thanks!

If you plan to use D8 you don't have to change the `anchor_scale` but I think you have to change the `pyramid_levels`, so in this case the correct formula should be:
```
# efficientdet8
INPUT_SIZE = 1536
# efficientdet default sizes
ANCHORS_SIZES = (4 * np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]) * 
                 np.array([2 ** 3, 2 ** 4, 2 ** 5, 2 ** 6, 2 ** 7, 2 ** 8])[:, np.newaxis]).flatten().tolist()
ANCHORS_SIZES
```
Where 2 ** 8 is for the sixth level:
`self.pyramid_levels = [5, 5, 5, 5, 5, 5, 5, 5, 6]`
```
        self.anchors = Anchors(anchor_scale=self.anchor_scale[compound_coef],
                               pyramid_levels=(torch.arange(self.pyramid_levels[self.compound_coef]) + 3).tolist(),
                               **kwargs)
```
`self.strides = kwargs.get('strides', [2 ** x for x in self.pyramid_levels])`

**Comment by mnslarcher** [comment]
I updated the tutorial @RomRoc, now you just have to specify PHI to change EfficientDet, let me know if you spot other errors

**Comment by RomRoc** [comment]
Now it's easier to use it, well done!

If you think it can be useful, I added some more logs that I need to know better my bboxes.

To know min and max sizes:
```
...
print(resized_bboxes[:5])
print("Min:", np.min(resized_bboxes))
print("Max:", np.max(resized_bboxes))
```

To know how many boxes without similar anchors:
```
...
print(bboxes[:5])
print("Total:", len(annotations))
```

Then, in my opinion, it's more interesting to calculate Bounding boxes without similar anchors after that boxes are adapted to the input size.
Let's consider a bbox in my dataset similar to an anchor, that after adapting to input size become to small for any anchor. In this case the `get_annotations_without_similar_anchors` function doesn't return this bbox, but it should be returned because when I train the bbox is resized. I'm I wrong?

Grazie

**Comment by mnslarcher** [comment]
> Then, in my opinion, it's more interesting to calculate Bounding boxes without similar anchors after that boxes are adapted to the input size.
> Let's consider a bbox in my dataset similar to an anchor, that after adapting to input size become to small for any anchor. In this case the `get_annotations_without_similar_anchors` function doesn't return this bbox, but it should be returned because when I train the bbox is resized. I'm I wrong?
> 
> Grazie

Mmm I'm not sure I'm getting your point @RomRoc, can you explain better?

Here:
```
from kmeans_anchors_ratios import get_annotations_without_similar_anchors


annotations = get_annotations_without_similar_anchors(
    instances,
    anchors_ratios,
    anchors_sizes=ANCHORS_SIZES,
    input_size=INPUT_SIZE,
    iou_threshold=0.5,
    min_size=0,
)

bboxes = [ann["bbox"][-2:] for ann in annotations]  # widths and heights
print("Bounding boxes without similar anchors (first 5):")
print(bboxes[:5])

instances_without_similar_anchors = instances.copy()
instances_without_similar_anchors["annotations"] = annotations
resized_bboxes = get_bboxes_adapted_to_input_size(instances_without_similar_anchors, input_size=INPUT_SIZE)
print("Bounding boxes without similar anchors adapted to the input size (first 5):")
print(resized_bboxes[:5])
```
`get_annotations_without_similar_anchors` gets you the **original** annotations that don't have similar anchors **after** their resizing based on the input size. So the returned annotations are at the original size but they are filtered considering their relation with the anchors after resizing them based on the input size. 

It's also interesting to look at the size of these "uncovered" annotations after resizing them, you can do this easily with `get_bboxes_adapted_to_input_size`as shown above.

Is this what you want?

**Comment by RomRoc** [comment]
You are absolutely right. I missed this part in your code: 

> **after** their resizing based on the input size

Thanks.
